;;; eno-loaddefs.el --- autogenerated file, do not edit
;;
;;; Code:

;;;### (autoloads nil "eno-version" "eno-version.el" (22933 42020
;;;;;;  455940 57000))
;;; Generated autoloads from eno-version.el

(autoload 'eno-release "eno-version" "\
The release version of Eno.
Inserted by installing Eno mode or when a release is made.

\(fn)" nil nil)

(autoload 'eno-git-version "eno-version" "\
The Git version of org-mode.
Inserted by installing Org or when a release is made.

\(fn)" nil nil)

(defvar eno-odt-data-dir "/usr/share/emacs/etc/eno" "\
The location of ODT styles.")

;;;***

;;;### (autoloads nil "eno" "eno.el" (22933 42016 699924 311000))
;;; Generated autoloads from eno.el

(autoload 'eno-version "eno" "\
Show the Eno version. This function is a version of `org-version' for Eno.
Show interactively, or when MESSAGE is non-nil, show it in echo
area.  With prefix argument, or when HERE is non-nil, insert it
at point.  In non-interactive uses, a reduced version string is
output unless FULL is given.

\(fn &optional HERE FULL MESSAGE)" t nil)

(autoload 'eno-mode "eno" "\
Eno is a free/libre personal information management system
centered around the idea of notes. It aims to help in getting the
right information at the right time, in the right place, in the
right form, and of sufficient completness and quality to perform
the current activity. 

eno-mode is part of Eno, and is a slight modification of org-mode.

\(fn)" t nil)

;;;***

(provide 'eno-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; eno-loaddefs.el ends here
