;;; eno-version.el --- autogenerated file, do not edit
;;
;;; Code:
;;;###autoload
(defun eno-release ()
  "The release version of Eno.
Inserted by installing Eno mode or when a release is made."
   (let ((eno-release "0.0.1"))
     eno-release))
;;;###autoload
(defun eno-git-version ()
  "The Git version of org-mode.
Inserted by installing Org or when a release is made."
   (let ((eno-git-version "N/A"))
     eno-git-version))
;;;###autoload
(defvar eno-odt-data-dir "/usr/share/emacs/etc/eno"
  "The location of ODT styles.")

(provide 'eno-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; coding: utf-8
;; End:
;;; eno-version.el ends here
